### ISSUE TITLE
Customer Orders in Database

### ISSUE THREAD

**Issue by jfelici4** [CS3250-IllegalSkillsException/myDatabase#22]
The finance, marketing, and sales departments want to understand customers better but need the historical data to do so. They want to have a database/pseudo-DB that stores all of the customer order information along with the time and date of their orders. [This database will grow each simulated “day”.]

**Comment by mesta88** [comment]
#34 Added search function in db.java that allows customers to view and filter customer order records, including any records added to the orders table

**Comment by jfelici4** [comment]
Resolved by #34 and #33
