### ISSUE TITLE
Data Governance for Customer Info

### ISSUE THREAD

**Issue by jfelici4** [CS3250-IllegalSkillsException/myDatabase#23]
For security and regulatory purposes, it is required that access to customer PII (personally identifiable information) be restricted (or is capable of being restricted). All data tables with customer info should use a separate look-up table (with fields: hashed_email and unhashed_email). The hashed email is the one that should be used in tables that have broader access (e.g. customer order information). The unhashed emails should only be the look-up table (and with more limited access – although don’t worry about permissions for our team projects). The customer should never see their hashed email of course, but behind the scenes (e.g. updating customer order history table), the hashed email should always be used.

**Comment by meddy7** [comment]
Tasking breakdown
McKenna:
* edit the menu class for the user interface
* 

Philip: 
*

**Comment by jfelici4** [comment]
About half way done with this after #32. Will need a pull request on the gist that @flip1012 made (https://gist.github.com/flip1012/4922055b148c5bd0d31a584f7c3383e4) at some point or another before we can truly close this issue.
