### ISSUE TITLE
Restructure Database class

### ISSUE THREAD

**Issue by richardoh95** [CS3250-IllegalSkillsException/myDatabase#66]
Database class seems to have become too large a bit of a "god class". Will need restructuring.

**Comment by jfelici4** [comment]
I will come up with some ideas and propose them throughout the week. It might blend over a bit between this sprint and the next.

**Comment by jfelici4** [comment]
![image](https://user-images.githubusercontent.com/76815354/113201525-d54df280-9226-11eb-9044-54337049b997.png)

This is an idea I had for how to restructure and reorganize things according to a new database class. I will also show this during the meeting.

**Comment by jfelici4** [comment]
Updated for new changes
![image](https://user-images.githubusercontent.com/76815354/113780004-c9ad7080-96eb-11eb-855a-b4312a0d635f.png)
