### ISSUE TITLE
Connecting users to database

### ISSUE THREAD

**Issue by flip1012** [CS3250-IllegalSkillsException/myDatabase#73]
Connecting the users to the database so that users are on a permissions basis.

Users will either receive Admin, Editor, or General User Titles

Each title will have a specific access to what can be edited in which table.

Fixing this should resolve the problem of having way to open access to all tables and being able to change whatever a user desires for better or for worse, and leaves all major changes to admins, with some specific changes that can be made by the editors, and restrictive access for General Users.

**Comment by richardoh95** [comment]
Issue removed from Sprint 4 to be addressed in a later sprint.

**Comment by flip1012** [comment]
issue will still be removed till a later sprint due to having close ties with data governance

**Comment by flip1012** [comment]
Will not be able to finish the issue before the end of the Sprint, putting it in as unresolved for now, and will close it. We will need to revisit this issue in the future.
